export const GET_QUOTE_DATA_REQUEST = "GET_QUOTE_DATA_REQUEST";
export const GET_QUOTE_DATA_SUCCESS = "GET_QUOTE_DATA_SUCCESS";
export const GET_QUOTE_DATA_FAILURE = "GET_QUOTE_DATA_FAILURE";
export const POST_QUOTE_DATA_REQUEST = "POST_QUOTE_DATA_REQUEST";
export const POST_QUOTE_DATA_SUCCESS = "POST_QUOTE_DATA_SUCCESS";
export const POST_QUOTE_DATA_FAILURE = "POST_QUOTE_DATA_FAILURE";
